# TODO Tasks

# Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_length(value,unit):

  """
  Converts length from m to ft and vice versa

  parameters :
  value -> float / int
  unit -> str -> m | ft

  returns a float

  """

  assert(isinstance(value,int) or isinstance(value,float)),ValueError("Value should be float or an integer")

  operations = {
      "m": value * 3.28084,
      "ft": value / 3.28084
  }

  if(unit not in operations):
    raise ValueError("Invalid Unit")


  return operations.get(unit)


def convert_weight(value,unit):


  """
  Converts weight from kg to lbs and vice versa

  parameters :
  value -> float | int
  unit -> str -> kg | lbs

  returns a float

  """

  assert(isinstance(value,int) or isinstance(value,float)),ValueError("Value should be float or an integer")

  operations = {
      "kg": value * 2.20462,
      "lbs": value / 2.20462
  }

  if(unit not in operations):
    raise ValueError("Invalid Unit")

  return operations.get(unit)


def convert_volume(value,unit):


  """
  Converts volume from l to gal and vice versa

  parameters :
  value -> float | int
  unit -> str -> l | ft

  returns a float

  """

  assert(isinstance(value,int) or isinstance(value,float)),ValueError("Value should be float or an integer")

  operations = {
      "l": value * 0.264172,
      "gal": value / 0.264172
  }

  if(unit not in operations):
    raise ValueError("Invalid Unit")

  return operations.get(unit)


def main():


  """
    Main function to handle all the user inputs and validations

  """

  choices = [1,2,3]

  print("Welcome to Unit Converter")
  print("You can choose what to convert")
  print("Enter 1 to convert length")
  print("Enter 2 to convert weight")
  print("Enter 3 to convert volume")

  user_choice = 0

  conversions = {
    1: "Enter m or ft",
    2: "Enter kg or lbs",
    3: "Enter l or gal"
  }

  conversion_functions = {
    1: convert_length,
    2: convert_weight,
    3: convert_volume
  }


  while True:
    try:

      user_choice = int(input("Enter a 1-3: "))

      if user_choice not in choices:
        raise ValueError("Not a valid choice enter different choice")


      value = float(input("Enter a valid value"))

      unit = input(conversions.get(user_choice)).strip().lower()

      result = conversion_functions.get(user_choice)(value,unit)

      print(f"The value has been converted from {value} to: {result}")
      return

    except ValueError as ve:
      print(f"Error: {ve} ")

    except AssertionError as ae:
      print(f"Error: {ae}")


main()


Welcome to Unit Converter
You can choose what to convert
Enter 1 to convert length
Enter 2 to convert weight
Enter 3 to convert volume
Enter a 1-3: 3
Enter a valid value809
Eneter L or Galgal
The value has been converted from 809.0 to: 3062.3987402147086


#Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def find_sum(arr):

  """
  Sums an list of numbers
  """
  sum = 0
  for e in arr:
    sum = sum + e
  return sum


def find_average(arr):

  """
  Finds the average of all the numbers in the list
  """
  sum = find_sum(arr)

  avg = sum / len(arr)

  return avg

def find_max(arr):


  """
  Finds the maximum value in an array
  """
  max = arr[0]

  for e in arr:
    if e > max:
      max = e

  return max

def find_min(arr):

  """
  Finds the mainimum value in an array
  """


  min = arr[0]

  for e in arr:
    if e < min:
      min = e
  return min


def main():

  """
  Main function to handle all the user inputs and validations
  """
  user_input = input("Enter list of numbers with spaces seprating each number:")

  numbers = list()
  try:
    numbers = [int(num) for num in user_input.split()]
  except ValueError as e:
    print("The numbers should be valid")
    return

  print("Enter 1 to find sum")
  print("Enter 2 to find average")
  print("Enter 3 to find maximum")
  print("Enter 4 to find minimum")

  choices = [1,2,3,4]

  operations = {
      1: find_sum,
      2: find_average,
      3: find_max,
      4: find_min
  }

  choice = 0
  try:
    choice = int(input("Enter a choice: "))

    if choice not in choices:
      print("Invalid choice")
      return
  except:
    print("Enter a number as a choice")
    return

  result = operations.get(choice)(numbers)

  print(f"The result is: {result}")

main()




Enter list of numbers with spaces seprating each number:7 43 23 2 5 55 88 902 
Enter 1 to find sum
Enter 2 to find average
Enter 3 to find maximum
Enter 4 to find minimum
Enter a choice: 1
The result is: 1125


# List operations

In [ ]:
def extract_every_other(lst):
  return lst[::2]

extract_every_other([1,2,3,4,5,6])

[1, 3, 5]

In [ ]:
def get_sublist(lst,start,end):
  return lst[start:end+1]

get_sublist([1,2,3,4,5,6],2,4)

[3, 4, 5]

In [ ]:
def reverse_list(lst):
  return lst[::-1]

reverse_list([1,2,3,4,5])

[5, 4, 3, 2, 1]

In [ ]:
def remove_first_last(lst):
  return lst[1:-1]

remove_first_last([1,2,3,4,5])

[2, 3, 4]

In [ ]:
def get_last_n(lst,n):
  return lst[-n:]

get_last_n([1,2,3,4,5],2)

[4, 5]

In [ ]:
def reverse_skip(lst):
  return lst[::-1][::2]

reverse_skip([1,2,3,4,5])

[5, 3, 1]

In [ ]:
def flatten(lst):
  flat_list = []
  for e in lst:
    if isinstance(e,list):
      flat_list.extend(flatten(e))
    else:
      flat_list.append(e)
  return flat_list

flatten([[1,2],[3,4],[5]])

[1, 2, 3, 4, 5]

In [ ]:
def access_nested_element(lst, indices):
  return lst[indices[0]][indices[1]]

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

access_nested_element(lst,[1,2])

6

In [ ]:
def sum_nester(lst):
  sum = 0
  for e in lst:
    if isinstance(e,list):
      sum += sum_nester(e)
    else:
      sum += e
  return sum

sum_nester([[1, 2], [3, [4, 5]], 6])

21

In [ ]:
def remove_element(lst,element):
  for e in lst:
    if isinstance(e,list):
      remove_element(e,element)
    else:
      if e == element:
        lst.remove(e)
  return lst

remove_element([[1, 2], [3, 2], [4, 5]],2)

[[1], [3], [4, 5]]

In [ ]:
def find_max(lst):

  flat_list = flatten(lst)

  return max(flat_list)

find_max([[1, 2], [3, [4, 5]], 6])

6

In [ ]:
def count_occurences(lst,elem):
  occ = 0

  for e in lst:
    if isinstance(e,list):
      occ += count_occurences(e,elem)
    else:
      if e == elem:
        occ += 1
  return occ

count_occurences([[1, 2], [2, 3], [2, 4]],2)

3

In [ ]:
def deep_flatten(lst):
  flat_list = []
  for e in lst:
    if isinstance(e,list):
      flat_list.extend(deep_flatten(e))
    else:
      flat_list.append(e)
  return flat_list

deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
def average_nested(lst):
  avg = 0
  flat_list = deep_flatten(lst)

  total = sum(flat_list)

  return total / len(flat_list)

average_nested([[1, 2], [3, 4], [5, 6]])

3.5

# TODO NUMPY

In [2]:
import numpy as np


Initialize an empty array with size 2X2.

In [3]:
array = np.empty((2,2))
array

array([[2.64498706e-316, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

Initialize an all one array with size 4X2.

In [11]:
array = np.ones((4,2))
array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [8]:
def full_array(shape,fill_value):
  return np.full(shape,fill_value)

full_array((2,2),3)

array([[3, 3],
       [3, 3]])

Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [12]:
def zeros_like(array):
  return np.zeros_like(array)

zeros_like(array)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [13]:
def ones_like(array):
  return np.ones_like(array)

ones_like(array)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [14]:
new_list = [1,2,3,4]

np_array = np.array(new_list)

np_array

array([1, 2, 3, 4])

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [15]:
array_with_range = np.arange(10,50)
array_with_range

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [16]:
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3X3 identity matrix.{Hint:np.eye()}

In [17]:
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [23]:
random_array = np.random.random(30)
random_array.mean()

0.5077427511260922

Create a 10X10 array with random values and find the minimum and maximum values.

In [24]:
ten_ten_mat = np.random.random(100).reshape(10,10)

print(f"The maximum value is {np.max(ten_ten_mat)} the minimum value is {np.min(ten_ten_mat)}")

The maximum value is 0.9827730323625011 the minimum value is 0.0191135083667221


Create a zero array of size 10 and replace 5th element with 1.

In [26]:
zero_array = np.zeros(10)
zero_array[4] = 1
zero_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Reverse an array arr = [1,2,0,0,4,0].

In [30]:
arr = [1,2,0,0,4,0]
np_arr = np.array(arr)
np_arr[::-1]

array([0, 4, 0, 0, 2, 1])

Create a 2d array with 1 on border and 0 inside.

In [34]:
def create_borderd_array(size):
  array = np.ones((size,size))
  array[1:-1,1:-1] = 0
  return array

create_borderd_array(4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

Create a 8X8 matrix and fill it with a checkerboard pattern.

In [39]:
def checkerboard_matrix(size):
  array = np.ones((size,size))
  array[::2,::2] = 0
  array[1::2,1::2] = 0
  return array

checkerboard_matrix(5)

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

In [41]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]]);
v = np.array([9,10])
w = np.array([11,12]);

In [42]:
def add_arrays(x,y):
  return x + y

add_arrays(x,y)

array([[ 6,  8],
       [10, 13]])

In [43]:
def sub_arrays(x,y):
  return x - y

sub_arrays(x,y)

array([[-4, -4],
       [-4, -3]])

In [45]:
def mult_arrays(x,y):
  return x * y

mult_arrays(x,y)

array([[ 5, 12],
       [21, 40]])

In [46]:
def sq_elements(x):
  return x ** 2

sq_elements(x)

array([[ 1,  4],
       [ 9, 25]])

In [48]:
xy_dot = np.dot(x,y)
vw_dot = np.dot(v,w)

print(f"The dot product of x and y is {xy_dot} and the dot product of v and w is {vw_dot}")

The dot product of x and y is [[19 22]
 [50 58]] and the dot product of v and w is 219


Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [49]:
concated = np.concatenate((x,y),axis=0)
concated

array([[1, 2],
       [3, 5],
       [5, 6],
       [7, 8]])

In [52]:
stacked = np.vstack((v,w))
stacked

array([[ 9, 10],
       [11, 12]])

In [53]:
conc_x_v = np.concatenate((x,v),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The dimension of both the supplied arrays should be equal to concatenate

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

In [55]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

Prove A.A−1 = I.

In [62]:
A_inv = np.linalg.inv(A)
A_A_inv = np.dot(A,A_inv)
I = np.eye(2)

is_identity = np.allclose(A_A_inv,I)

if is_identity:
  print("A.A^ = I")
else:
  print(" A.A^ != I")

A.A^ = I


Prove AB ̸= BA.

In [66]:
AB = np.dot(A,B)
BA = np.dot(B,A)

is_equal = np.allclose(AB,BA)

if is_equal:
  print("AB == BA")
else:
  print("AB != BA")

AB != BA


Prove (AB)

T = BTAT
.

In [75]:
A_T = A.T
B_T = B.T

AB = np.dot(A,B)
AB_T = AB.T
BTAT = np.dot(B_T,A_T)

is_equal = np.allclose(AB_T,BTAT)

if is_equal:
  print("(AB)^T == BTAT")
else:
  print("(AB)^T != BTAT")


(AB)^T == BTAT


2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [80]:
# solving by inverse matrix method X = AinvB

a = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
b = np.array([-1,-3,9]).T

x = np.dot(np.linalg.inv(a),b)

print(f"The solution is {x}")

The solution is [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [86]:
import time

In [93]:
iteration = 1000000
def list_add():

  lst_1 = [e for e in range(iteration)]
  lst_2 = [e for e in range(iteration)]
  start = time.time()


  lst_3 = [lst_1[i] + lst_2[i] for i in range(iteration)]

  end = time.time()
  return end-start


clocked_time = list_add()

print(f"The program took {clocked_time} seconds")

The program took 0.08001112937927246 seconds


In [94]:
def list_add_np():
  lst_1 = np.arange(iteration)
  lst_2 = np.arange(iteration)

  start = time.time()


  lst_3 = lst_1 + lst_2

  end = time.time()
  return end-start

clocked_time = list_add_np()

print(f"The program took {clocked_time} seconds")

The program took 0.003625154495239258 seconds


In [98]:
def list_mult():
  lst_1 = [e for e in range(iteration)]
  lst_2 = [e for e in range(iteration)]

  start = time.time()

  lst_3 = [lst_1[i] * lst_2[i] for i in range(iteration)]

  end = time.time()
  return end-start

clocked_time = list_mult()

print(f"The program took {clocked_time} seconds")

The program took 0.08362579345703125 seconds


In [100]:
def list_mult_np():
  lst_1 = np.arange(iteration)
  lst_2 = np.arange(iteration)

  start = time.time()


  lst_3 = lst_1 * lst_2

  end = time.time()
  return end-start

clocked_time = list_mult_np()

print(f"The program took {clocked_time} seconds")

The program took 0.00438237190246582 seconds


In [102]:
def list_dot():
  lst_1 = [e for e in range(iteration)]
  lst_2 = [e for e in range(iteration)]

  start = time.time()


  dot = sum(lst_1[i] * lst_2[i] for i in range(iteration) )

  end = time.time()
  return dot,end-start


dot, clocked_time = list_dot()

print(f"The program took {clocked_time} seconds")
print(f"Dot product {dot}")

The program took 0.3253974914550781 seconds
Dot product 333332833333500000


In [103]:
def list_dot_np():
  lst_1 = np.arange(iteration)
  lst_2 = np.arange(iteration)

  start = time.time()


  dot = np.dot(lst_1,lst_2)

  end = time.time()
  return dot,end-start


dot, clocked_time = list_dot_np()

print(f"The program took {clocked_time} seconds")
print(f"Dot product {dot}")

The program took 0.0020639896392822266 seconds
Dot product 333332833333500000


In [110]:
def mult_large_matrix():


  size = 1000
  mat_1 =[[i for i in range(size)] for _ in range(size)]
  mat_2 =[[i for i in range(size)] for _ in range(size)]
  result = [[0 for _ in range(size)] for _ in range(size)]
  start = time.time()


  for row in range(size):
    for col in range(size):
      val = 0
      for k in range(size):
        val = val + mat_1[row][k] * mat_2[k][col]
      result[row][col] = val

  end = time.time()
  return end-start

clocked_time = mult_large_matrix()

print(f"The program took {clocked_time} seconds")


The program took 161.76419162750244 seconds


In [109]:
def mult_large_mat_np():

  size = 1000

  mat_1 = np.arange(size * size).reshape((1000,1000))
  mat_2 = np.arange(size * size).reshape((1000,1000))

  start = time.time()

  result = np.dot(mat_1,mat_2)

  end = time.time()
  return end-start


clocked_time = mult_large_mat_np()

print(f"The program took {clocked_time} seconds")

The program took 2.271050214767456 seconds
